import "dotenv/config";
import db from "../config/db.js";

const formatToMySQLDate = (dateString) => {
  // 1. Remove the ordinal suffixes (st, nd, rd, th)
  // "12th September 2020" becomes "12 September 2020"
  const cleanDateStr = dateString.replace(/(\d+)(st|nd|rd|th)/, "$1");

  // 2. Let JavaScript parse the clean string
  const dateObj = new Date(cleanDateStr);

  // 3. Format to YYYY-MM-DD safely handling leading zeros
  const year = dateObj.getFullYear();
  const month = String(dateObj.getMonth() + 1).padStart(2, "0");
  const day = String(dateObj.getDate()).padStart(2, "0");

  return `${year}-${month}-${day}`;
};

const patients = [
  {
    hospitalId: "1AFHFH093",
    patientName: "Oluwaseun Aregbesola",
    phoneNumber: "+2347068642920",
    gender: "Male",
    nextDeliveryDate: "12th September 2020",
    location: "VI, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Stella Omotoye",
    phoneNumber: "+2347068642920",
    gender: "Female",
    nextDeliveryDate: "12th September 2020",
    location: "VI, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Chinyere Okafor",
    phoneNumber: "+2347068642920",
    gender: "Female",
    nextDeliveryDate: "12th September 2020",
    location: "Yaba, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Mohammed Danladi",
    phoneNumber: "+2347068642920",
    gender: "Male",
    nextDeliveryDate: "12th September 2020",
    location: "Gbagada, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Michael Aribisala",
    phoneNumber: "+2347068642920",
    gender: "Male",
    nextDeliveryDate: "12th September 2020",
    location: "VI, Lagos",
    paymentStatus: "Paid",
    status: "Assigned",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Donatus Emefiele",
    phoneNumber: "+2347068642920",
    gender: "Male",
    nextDeliveryDate: "12th September 2020",
    location: "Ikorodu, Lagos",
    paymentStatus: "Unpaid",
    status: "Assigned",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Donatus Emefiele",
    phoneNumber: "+2347068642920",
    gender: "Male",
    nextDeliveryDate: "12th September 2020",
    location: "VI, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Donatus Emefiele",
    phoneNumber: "+2347068642920",
    gender: "Male",
    nextDeliveryDate: "12th September 2020",
    location: "VI, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Donatus Emefiele",
    phoneNumber: "+2347068642920",
    gender: "Male",
    nextDeliveryDate: "12th September 2020",
    location: "VI, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Donatus Emefiele",
    phoneNumber: "+2347068642920",
    gender: "Male",
    nextDeliveryDate: "12th September 2020",
    location: "VI, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Amina Bello",
    phoneNumber: "+2348031234567",
    gender: "Female",
    nextDeliveryDate: "18th March 2026",
    location: "Ikeja, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Chukwudi Eze",
    phoneNumber: "+2348129876543",
    gender: "Male",
    nextDeliveryDate: "20th March 2026",
    location: "Lekki, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Folashade Adeleke",
    phoneNumber: "+2347055554444",
    gender: "Female",
    nextDeliveryDate: "22nd March 2026",
    location: "Surulere, Lagos",
    paymentStatus: "Paid",
    status: "Assigned",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Nnamdi Kalu",
    phoneNumber: "+2349098887777",
    gender: "Male",
    nextDeliveryDate: "25th March 2026",
    location: "Ajah, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Zainab Usman",
    phoneNumber: "+2348023332222",
    gender: "Female",
    nextDeliveryDate: "1st April 2026",
    location: "Festac, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Olamilekan Bakare",
    phoneNumber: "+2347081112233",
    gender: "Male",
    nextDeliveryDate: "5th April 2026",
    location: "Oshodi, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Ngozi Nwosu",
    phoneNumber: "+2348145556677",
    gender: "Female",
    nextDeliveryDate: "10th April 2026",
    location: "Maryland, Lagos",
    paymentStatus: "Unpaid",
    status: "Assigned",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Tunde Owolabi",
    phoneNumber: "+2349021113344",
    gender: "Male",
    nextDeliveryDate: "12th April 2026",
    location: "Yaba, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Aisha Ibrahim",
    phoneNumber: "+2348067778899",
    gender: "Female",
    nextDeliveryDate: "15th April 2026",
    location: "VI, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Kelechi Anyanwu",
    phoneNumber: "+2347034445566",
    gender: "Male",
    nextDeliveryDate: "20th April 2026",
    location: "Ikorodu, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Amina Bello",
    phoneNumber: "+2348031234567",
    gender: "Female",
    nextDeliveryDate: "18th March 2026",
    location: "Ikeja, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Chukwudi Eze",
    phoneNumber: "+2348129876543",
    gender: "Male",
    nextDeliveryDate: "20th March 2026",
    location: "Lekki, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Folashade Adeleke",
    phoneNumber: "+2347055554444",
    gender: "Female",
    nextDeliveryDate: "22nd March 2026",
    location: "Surulere, Lagos",
    paymentStatus: "Unpaid",
    status: "Assigned",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Nnamdi Kalu",
    phoneNumber: "+2349098887777",
    gender: "Male",
    nextDeliveryDate: "25th March 2026",
    location: "Ajah, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Zainab Usman",
    phoneNumber: "+2348023332222",
    gender: "Female",
    nextDeliveryDate: "1st April 2026",
    location: "Festac, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Olamilekan Bakare",
    phoneNumber: "+2347081112233",
    gender: "Male",
    nextDeliveryDate: "5th April 2026",
    location: "Oshodi, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Ngozi Nwosu",
    phoneNumber: "+2348145556677",
    gender: "Female",
    nextDeliveryDate: "10th April 2026",
    location: "Maryland, Lagos",
    paymentStatus: "Paid",
    status: "Assigned",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Tunde Owolabi",
    phoneNumber: "+2349021113344",
    gender: "Male",
    nextDeliveryDate: "12th April 2026",
    location: "Yaba, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Aisha Ibrahim",
    phoneNumber: "+2348067778899",
    gender: "Female",
    nextDeliveryDate: "15th April 2026",
    location: "VI, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Kelechi Anyanwu",
    phoneNumber: "+2347034445566",
    gender: "Male",
    nextDeliveryDate: "20th April 2026",
    location: "Ikorodu, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "5QWERT222",
    patientName: "Dayo Johnson",
    phoneNumber: "+2348055551122",
    gender: "Male",
    nextDeliveryDate: "22nd April 2026",
    location: "Gbagada, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "7TYUIO111",
    patientName: "Fatima Sani",
    phoneNumber: "+2349033334455",
    gender: "Female",
    nextDeliveryDate: "25th April 2026",
    location: "Ikoyi, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Emeka Okafor",
    phoneNumber: "+2347066667788",
    gender: "Male",
    nextDeliveryDate: "28th April 2026",
    location: "Magodo, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Bisi Akande",
    phoneNumber: "+2348122223344",
    gender: "Female",
    nextDeliveryDate: "1st May 2026",
    location: "Ogba, Lagos",
    paymentStatus: "Unpaid",
    status: "Assigned",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Musa Danjuma",
    phoneNumber: "+2348099990011",
    gender: "Male",
    nextDeliveryDate: "3rd May 2026",
    location: "Agege, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Funke Ojo",
    phoneNumber: "+2347011112233",
    gender: "Female",
    nextDeliveryDate: "5th May 2026",
    location: "Apapa, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "5QWERT222",
    patientName: "Chinedu Obinna",
    phoneNumber: "+2349088889900",
    gender: "Male",
    nextDeliveryDate: "8th May 2026",
    location: "Mushin, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "7TYUIO111",
    patientName: "Halima Abubakar",
    phoneNumber: "+2348044445566",
    gender: "Female",
    nextDeliveryDate: "10th May 2026",
    location: "Somolu, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Segun Awolowo",
    phoneNumber: "+2348155556677",
    gender: "Male",
    nextDeliveryDate: "12th May 2026",
    location: "Isolo, Lagos",
    paymentStatus: "Paid",
    status: "Assigned",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Chioma Nnadi",
    phoneNumber: "+2347022223344",
    gender: "Female",
    nextDeliveryDate: "15th May 2026",
    location: "Ejigbo, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Yemi Alade",
    phoneNumber: "+2349055556677",
    gender: "Female",
    nextDeliveryDate: "18th May 2026",
    location: "Ikeja, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Obi Chukwu",
    phoneNumber: "+2348077778899",
    gender: "Male",
    nextDeliveryDate: "20th May 2026",
    location: "Lekki, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "5QWERT222",
    patientName: "Tope Alabi",
    phoneNumber: "+2348188889900",
    gender: "Female",
    nextDeliveryDate: "22nd May 2026",
    location: "Surulere, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "7TYUIO111",
    patientName: "Ibrahim Babangida",
    phoneNumber: "+2347099990011",
    gender: "Male",
    nextDeliveryDate: "25th May 2026",
    location: "Ajah, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Nkechi Amadi",
    phoneNumber: "+2349011112233",
    gender: "Female",
    nextDeliveryDate: "28th May 2026",
    location: "Festac, Lagos",
    paymentStatus: "Unpaid",
    status: "Assigned",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Damilola Adeyemi",
    phoneNumber: "+2348033334455",
    gender: "Female",
    nextDeliveryDate: "1st June 2026",
    location: "Oshodi, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Sani Mohammed",
    phoneNumber: "+2348166667788",
    gender: "Male",
    nextDeliveryDate: "3rd June 2026",
    location: "Maryland, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Kemi Olunloyo",
    phoneNumber: "+2347044445566",
    gender: "Female",
    nextDeliveryDate: "5th June 2026",
    location: "Yaba, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "5QWERT222",
    patientName: "Uche Okoro",
    phoneNumber: "+2349066667788",
    gender: "Male",
    nextDeliveryDate: "8th June 2026",
    location: "VI, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "7TYUIO111",
    patientName: "Adebayo Salami",
    phoneNumber: "+2348022223344",
    gender: "Male",
    nextDeliveryDate: "10th June 2026",
    location: "Ikorodu, Lagos",
    paymentStatus: "Paid",
    status: "Assigned",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Grace Odemwingie",
    phoneNumber: "+2348133334455",
    gender: "Female",
    nextDeliveryDate: "12th June 2026",
    location: "Gbagada, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Victor Moses",
    phoneNumber: "+2347055556677",
    gender: "Male",
    nextDeliveryDate: "15th June 2026",
    location: "Ikoyi, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Blessing Okagbare",
    phoneNumber: "+2349044445566",
    gender: "Female",
    nextDeliveryDate: "18th June 2026",
    location: "Magodo, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Sunday Oliseh",
    phoneNumber: "+2348088889900",
    gender: "Male",
    nextDeliveryDate: "20th June 2026",
    location: "Ogba, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "5QWERT222",
    patientName: "Mercy Johnson",
    phoneNumber: "+2348177778899",
    gender: "Female",
    nextDeliveryDate: "22nd June 2026",
    location: "Agege, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "7TYUIO111",
    patientName: "Kanayo O. Kanayo",
    phoneNumber: "+2347011113344",
    gender: "Male",
    nextDeliveryDate: "25th June 2026",
    location: "Apapa, Lagos",
    paymentStatus: "Unpaid",
    status: "Assigned",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Genevieve Nnaji",
    phoneNumber: "+2349022224455",
    gender: "Female",
    nextDeliveryDate: "28th June 2026",
    location: "Mushin, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Ramsey Nouah",
    phoneNumber: "+2348099991122",
    gender: "Male",
    nextDeliveryDate: "1st July 2026",
    location: "Somolu, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Omotola Jalade",
    phoneNumber: "+2348144445566",
    gender: "Female",
    nextDeliveryDate: "3rd July 2026",
    location: "Isolo, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Richard Mofe",
    phoneNumber: "+2347033334455",
    gender: "Male",
    nextDeliveryDate: "5th July 2026",
    location: "Ejigbo, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "5QWERT222",
    patientName: "Rita Dominic",
    phoneNumber: "+2349077778899",
    gender: "Female",
    nextDeliveryDate: "8th July 2026",
    location: "Ikeja, Lagos",
    paymentStatus: "Paid",
    status: "Assigned",
  },
  {
    hospitalId: "7TYUIO111",
    patientName: "Desmond Elliot",
    phoneNumber: "+2348055556677",
    gender: "Male",
    nextDeliveryDate: "10th July 2026",
    location: "Lekki, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Ini Edo",
    phoneNumber: "+2348122225566",
    gender: "Female",
    nextDeliveryDate: "12th July 2026",
    location: "Surulere, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Chinedu Ikedieze",
    phoneNumber: "+2347088889900",
    gender: "Male",
    nextDeliveryDate: "15th July 2026",
    location: "Ajah, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Osita Iheme",
    phoneNumber: "+2349011114455",
    gender: "Male",
    nextDeliveryDate: "18th July 2026",
    location: "Festac, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Pete Edochie",
    phoneNumber: "+2348066667788",
    gender: "Male",
    nextDeliveryDate: "20th July 2026",
    location: "Oshodi, Lagos",
    paymentStatus: "Paid",
    status: "Assigned",
  },
  {
    hospitalId: "5QWERT222",
    patientName: "Nkem Owoh",
    phoneNumber: "+2348133336677",
    gender: "Male",
    nextDeliveryDate: "22nd July 2026",
    location: "Maryland, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "7TYUIO111",
    patientName: "Olu Jacobs",
    phoneNumber: "+2347099992233",
    gender: "Male",
    nextDeliveryDate: "25th July 2026",
    location: "Yaba, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Joke Silva",
    phoneNumber: "+2349055558899",
    gender: "Female",
    nextDeliveryDate: "28th July 2026",
    location: "VI, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Liz Benson",
    phoneNumber: "+2348044447788",
    gender: "Female",
    nextDeliveryDate: "1st August 2026",
    location: "Ikorodu, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Sam Loco",
    phoneNumber: "+2348111112233",
    gender: "Male",
    nextDeliveryDate: "3rd August 2026",
    location: "Gbagada, Lagos",
    paymentStatus: "Unpaid",
    status: "Assigned",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Justus Esiri",
    phoneNumber: "+2347077778899",
    gender: "Male",
    nextDeliveryDate: "5th August 2026",
    location: "Ikoyi, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "5QWERT222",
    patientName: "Enebeli Elebuwa",
    phoneNumber: "+2349033336677",
    gender: "Male",
    nextDeliveryDate: "8th August 2026",
    location: "Magodo, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "7TYUIO111",
    patientName: "Bukky Wright",
    phoneNumber: "+2348088881122",
    gender: "Female",
    nextDeliveryDate: "10th August 2026",
    location: "Ogba, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Faithia Balogun",
    phoneNumber: "+2348155558899",
    gender: "Female",
    nextDeliveryDate: "12th August 2026",
    location: "Agege, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Sola Sobowale",
    phoneNumber: "+2347022225566",
    gender: "Female",
    nextDeliveryDate: "15th August 2026",
    location: "Apapa, Lagos",
    paymentStatus: "Paid",
    status: "Assigned",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Jide Kosoko",
    phoneNumber: "+2349066669900",
    gender: "Male",
    nextDeliveryDate: "18th August 2026",
    location: "Mushin, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Adebayo Salami",
    phoneNumber: "+2348011112233",
    gender: "Male",
    nextDeliveryDate: "20th August 2026",
    location: "Somolu, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "5QWERT222",
    patientName: "Taiwo Hassan",
    phoneNumber: "+2348199990011",
    gender: "Male",
    nextDeliveryDate: "22nd August 2026",
    location: "Isolo, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "7TYUIO111",
    patientName: "Yinka Quadri",
    phoneNumber: "+2347044447788",
    gender: "Male",
    nextDeliveryDate: "25th August 2026",
    location: "Ejigbo, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Babatunde Omidina",
    phoneNumber: "+2349088881122",
    gender: "Male",
    nextDeliveryDate: "28th August 2026",
    location: "Ikeja, Lagos",
    paymentStatus: "Unpaid",
    status: "Assigned",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Bolaji Amusan",
    phoneNumber: "+2348055559900",
    gender: "Male",
    nextDeliveryDate: "1st September 2026",
    location: "Lekki, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Odunlade Adekola",
    phoneNumber: "+2348122226677",
    gender: "Male",
    nextDeliveryDate: "3rd September 2026",
    location: "Surulere, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Femi Adebayo",
    phoneNumber: "+2347066669900",
    gender: "Male",
    nextDeliveryDate: "5th September 2026",
    location: "Ajah, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "5QWERT222",
    patientName: "Muyiwa Ademola",
    phoneNumber: "+2349011115566",
    gender: "Male",
    nextDeliveryDate: "8th September 2026",
    location: "Festac, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "7TYUIO111",
    patientName: "Saheed Balogun",
    phoneNumber: "+2348099993344",
    gender: "Male",
    nextDeliveryDate: "10th September 2026",
    location: "Oshodi, Lagos",
    paymentStatus: "Paid",
    status: "Assigned",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Kolawole Ajeyemi",
    phoneNumber: "+2348144448899",
    gender: "Male",
    nextDeliveryDate: "12th September 2026",
    location: "Maryland, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Lateef Adedimeji",
    phoneNumber: "+2347033336677",
    gender: "Male",
    nextDeliveryDate: "15th September 2026",
    location: "Yaba, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Afeez Oyetoro",
    phoneNumber: "+2349077770011",
    gender: "Male",
    nextDeliveryDate: "18th September 2026",
    location: "VI, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Hafiz Oyetoro",
    phoneNumber: "+2348022225566",
    gender: "Male",
    nextDeliveryDate: "20th September 2026",
    location: "Ikorodu, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "5QWERT222",
    patientName: "Charles Inojie",
    phoneNumber: "+2348188882233",
    gender: "Male",
    nextDeliveryDate: "22nd September 2026",
    location: "Gbagada, Lagos",
    paymentStatus: "Paid",
    status: "Assigned",
  },
  {
    hospitalId: "7TYUIO111",
    patientName: "John Okafor",
    phoneNumber: "+2347011115566",
    gender: "Male",
    nextDeliveryDate: "25th September 2026",
    location: "Ikoyi, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Victor Osuagwu",
    phoneNumber: "+2349044448899",
    gender: "Male",
    nextDeliveryDate: "28th September 2026",
    location: "Magodo, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Francis Odega",
    phoneNumber: "+2348066661122",
    gender: "Male",
    nextDeliveryDate: "1st October 2026",
    location: "Ogba, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "2BGHJK104",
    patientName: "Bishop Umoh",
    phoneNumber: "+2348133339900",
    gender: "Male",
    nextDeliveryDate: "3rd October 2026",
    location: "Agege, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
  {
    hospitalId: "9XCVBN442",
    patientName: "Samuel Ajibola",
    phoneNumber: "+2347055558899",
    gender: "Male",
    nextDeliveryDate: "5th October 2026",
    location: "Apapa, Lagos",
    paymentStatus: "Unpaid",
    status: "Assigned",
  },
  {
    hospitalId: "5QWERT222",
    patientName: "Williams Uchemba",
    phoneNumber: "+2349099992233",
    gender: "Male",
    nextDeliveryDate: "8th October 2026",
    location: "Mushin, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "7TYUIO111",
    patientName: "Broda Shaggi",
    phoneNumber: "+2348077771122",
    gender: "Male",
    nextDeliveryDate: "10th October 2026",
    location: "Somolu, Lagos",
    paymentStatus: "Paid",
    status: "Due",
  },
  {
    hospitalId: "1AFHFH093",
    patientName: "Debo Adedayo",
    phoneNumber: "+2348122229900",
    gender: "Male",
    nextDeliveryDate: "12th October 2026",
    location: "Isolo, Lagos",
    paymentStatus: "Paid",
    status: "Completed",
  },
  {
    hospitalId: "3MNBVC999",
    patientName: "Mark Angel",
    phoneNumber: "+2347088882233",
    gender: "Male",
    nextDeliveryDate: "15th October 2026",
    location: "Ejigbo, Lagos",
    paymentStatus: "Unpaid",
    status: "Due",
  },
];

const seedDatabase = async () => {
  console.log("Starting database seeding...");

  try {
    for (const patient of patients) {
      await db.execute(
        `INSERT INTO patients 
                (hospitalId, patientName, phoneNumber, gender, nextDeliveryDate, location, paymentStatus, status) 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          patient.hospitalId,
          patient.patientName,
          patient.phoneNumber,
          patient.gender,
          formatToMySQLDate(patient.nextDeliveryDate),
          patient.location,
          patient.paymentStatus,
          patient.status,
        ],
      );
    }
    console.log("✅ All patients successfully inserted into the database!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error.message);
    process.exit(1);
  }
};

seedDatabase();
